---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "ctse-stock-server-service"
  namespace: "default"
  labels:
    app: "ctse-stock-server"
spec:
  ports:
  - protocol: "TCP"
    port: 5000
  selector:
    app: "ctse-stock-server"
  type: "ClusterIP"
